name: Verify

on:
  pull_request:
    branches: [ dev ]
    types: [ opened, reopened, synchronize, ready_for_review ]

jobs:
  verify:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.13.1'

      - name: Install Dependencies
        run: yarn install

      - name: Code Style Check
        run: yarn lint
        env:
          CI: true
